// page determiner activite
export const LISTE_SECTION_ACTIVITE="LISTE_SECTION_ACTIVITE"
export const LISTE_GROUPE_ACTIVITE="LISTE_GROUPE_ACTIVITE"
export const LISTE_DIVISION_ACTIVITE="LISTE_DIVISION_ACTIVITE"
export const LISTE_CLASSE_ACTIVITE="LISTE_CLASSE_ACTIVITE"
export const LISTE_CATEGORIE_ACTIVITE="LISTE_CATEGORIE_ACTIVITE"